### ISSUE TITLE
AssertionError: missing some sentences

### ISSUE THREAD

**Issue by akkarimi** [jerbarnes/semeval22_structured_sentiment#10]
I'm trying to submit some results, but I get assertion error telling me that some sentences are missing.
I tried it with a previously successful submission and I still got the same error. Is there a problem with codalab evaluation?

**Comment by jerbarnes** [comment]
Hi,

We have recently updated the darmstadt and mpqa datasets, which is probably what led to this error. You can check the sentence ids in the example_submission.zip and make sure that yours coincide. It might be worth making sure that the github is up-to-date. Let me know if that solves the issue.

**Comment by akutuzov** [comment]
Hi @akkarimi 
In your submissions, there  are 1622 sentences in the MPQA dataset, while there should be 2063 of them.
Check why is it like that.
