### ISSUE TITLE
problems in submitting zip file

### ISSUE THREAD

**Issue by BogdanSemenov** [jerbarnes/semeval22_structured_sentiment#15]
Create the right structured zip file and send it to CodaLab. 
Get mistake:

`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpSeGUFE/run/program/evaluate.py", line 272, in 
    main()
  File "/tmp/codalab/tmpSeGUFE/run/program/evaluate.py", line 236, in main
    with open(submission_answer_file) as infile:
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmpSeGUFE/run/input/res/monolingual/norec/predictions.json'`

Compare with your example `example_submission.zip` and it is okay. The same file's naming. The same structure. Everything is the same. 
Send your example and it is okay for the system. But when I unzip it and again zip it is the same mistake. 

What am I doing wrong?

**Comment by akutuzov** [comment]
Are you sure you have the correct directory structure in your submission?

**Comment by BogdanSemenov** [comment]
Yes. I tried to send example_submission.zip. It was okay. After that, I unzipped it and again zipped it. And also sent it to the system. It was failed with the same mistake.

**Comment by jerbarnes** [comment]
Hmm, when you rezip the file, do you select a) crosslingual and monolingual and then zip these to a file called submission.zip or do you b) select example_submission and zip this? 

The second way will break the directory structure after rezipping.

**Comment by BogdanSemenov** [comment]
Yes, thank you. a) variant is the right.
