### ISSUE TITLE
Request for requirements.txt for baseline codes

### ISSUE THREAD

**Issue by luxinyu1** [jerbarnes/semeval22_structured_sentiment#18]
I am keeping encountering bugs caused by version mismatch (torch torchtext & numpy) while reproducing baselines results. Could you please provide us a package version config file (such as requirements.txt) so that we can run the baseline codes more smoothly?

**Comment by jerbarnes** [comment]
Hi,

Sorry for the late response, but I have now added requirements.txt for the two baselines.

**Comment by luxinyu1** [comment]
Thanks a lot 👍

**Comment by luxinyu1** [comment]
> Hi,
> 
> Sorry for the late response, but I have now added requirements.txt for the two baselines.

Thanks a lot 👍
