### ISSUE TITLE
Processing Darmstadt on OSX

### ISSUE THREAD

**Issue by amith-ananthram** [jerbarnes/semeval22_structured_sentiment#2]
Hey there,

Thanks for the great repo!  Just wanted to point out a little issue with processing the Darmstadt files on OSX.  On OSX the sed command works a little differently so line 20 of process_darmstadt.sh should be:

```
grep -rl "&" universities/basedata | xargs sed -i '' -e 's/&/and/g'
```

Here's an explanation on StackOverflow: https://stackoverflow.com/questions/19456518/error-when-using-sed-with-find-command-on-os-x-invalid-command-code

Otherwise the script fails with the following error due to the rogue ampersands in the XML file:

```
...
  inflating: universities/customization/SentenceOpinionAnalysisResult_customization.xml  
sed: 1: "universities/basedata/U ...": invalid command code u
Traceback (most recent call last):
  File "/Users/amith/Documents/columbia/phd/sourceid/corpora/semeval22_structured_sentiment/data/darmstadt_unis/process_darmstadt.py", line 475, in <module>
    o = get_opinions(bfile, mfile)
  File "/Users/amith/Documents/columbia/phd/sourceid/corpora/semeval22_structured_sentiment/data/darmstadt_unis/process_darmstadt.py", line 113, in get_opinions
    text += token + " "
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Happy to open a PR with the change (tried pushing a branch but I think the repo is restricted).

**Comment by jerbarnes** [comment]
Hi,

Thanks for pointing out the code doesn't work on OSX! Feel free to open a pull request.

**Comment by jerbarnes** [comment]
Ok, in the end, I just added the code, so I'll close this issue now.

**Comment by jerbarnes** [comment]
In the end, the OSX solution didn't work with other systems. So I created a separate script for the OSX solution (process_darmstadt_OSX.sh).

**Comment by amith-ananthram** [comment]
Thanks Jeremy!
