### ISSUE TITLE
null values in MPQA dataset

### ISSUE THREAD

**Issue by luxinyu1** [jerbarnes/semeval22_structured_sentiment#20]
```null``` values exist both in keys ```Intensity``` and ```Polarity``` in MPQA dataset.
This bug occurs in the newest commit ```99f2f885aba188a52afeb9523cc9b9d194465d85```.

**Comment by jerbarnes** [comment]
Hi,

Thank you for pointing this out. I've just updated the process_mpqa.py script to remove any annotations with null polarity. For other datasets, I've manually corrected any occurrences as well. For intensity, I have not removed them, as we do not explicitly use this feature in the current shared task, but we will need to keep this in mind for any future iterations.

**Comment by luxinyu1** [comment]
Thanks for your revision, I believe this issue has been solved.

**Comment by luxinyu1** [comment]
> Hi,
> 
> Thank you for pointing this out. I've just updated the process_mpqa.py script to remove any annotations with null polarity. For other datasets, I've manually corrected any occurrences as well. For intensity, I have not removed them, as we do not explicitly use this feature in the current shared task, but we will need to keep this in mind for any future iterations.

Thanks for your revision, I believe this issue has been solved.
