### ISSUE TITLE
Some details about data

### ISSUE THREAD

**Issue by luxinyu1** [jerbarnes/semeval22_structured_sentiment#22]
In the monolingual subsection in README, there's a sentence:

``This track assumes that you train and test on the same language.`` 

Does this mean we can use extra training data in the same language other than the given training set? For example, can we use MPQA+Opener_en training set (or some other mined data in English) to train models and test on MPQA?

**Comment by jerbarnes** [comment]
Yes, in the monolingual subtrack you can use any combination of resources, including the other structured sentiment datasets. We only require that you document and cite these extra resources in detail.

**Comment by luxinyu1** [comment]
We got it, thanks for your reply.

**Comment by janpf** [comment]
@jerbarnes 
> Yes, in the monolingual subtrack you can use any combination of resources, including the other structured sentiment datasets.

... those which are in other languages as well?
This would be contrary to

> This track assumes that you train and test on the same language.

Thanks :)

**Comment by jerbarnes** [comment]
When we introduced the monolingual subtrack, we had not thought about people using multi-lingual LMs in this track. The wording therefore sounds a bit more restrictive than intended. Sorry for that and I hope our leniency in this respect has not caused you any large problems...
