### ISSUE TITLE
Conflicting data usage rules about crosslingual task

### ISSUE THREAD

**Issue by luxinyu1** [jerbarnes/semeval22_structured_sentiment#28]
In ```./README.md``` the data usage rule about subtask 2 is:
```
For training, you can use any of the other datasets, as well as any other resource that does not contain sentiment annotations in the target language.
````
In ```./data/README.md``` the data usage rule about subtask 2 is:
```
This track will instead train only on a high-resource language (English) and test on several languages.
```
From my perspective, these two descriptions are quite different. We have spent a lot of time optimizing our cross-lingual model under the rule in ```./README.md```. And now it is the evaluation phase, we hope that there's a solution that fairly merges the results under different rules.

**Comment by jerbarnes** [comment]
The rules in the full readme are the valid ones. I've changed the information in the data/README.md to reflect this.

**Comment by luxinyu1** [comment]
> The rules in the full readme are the valid ones. I've changed the information in the data/README.md to reflect this.

Happy to hear this, thanks for your reply.
