### ISSUE TITLE
Difference in MPQA test set

### ISSUE THREAD

**Issue by ybz79** [jerbarnes/semeval22_structured_sentiment#29]
Hi, I used the provided script process_mpqa.sh to process the mpqa dataset and get 2058 sentences. However, I found that the test set of mpqa in example submission has 2111 sentences. Several sentences are missed:

![image](https://user-images.githubusercontent.com/46948783/150741079-06012921-8fe6-49dc-9760-2261a5e3fa90.png)

How can I fix this?

**Comment by jerbarnes** [comment]
Hi,

Sorry to hear you are having problems. Can you confirm that your stanza version is 1.1.1?

**Comment by ybz79** [comment]
thanks, I changed the stanza version to 1.1.1 and the sentence number is correct now
