### ISSUE TITLE
MPQA dev split has no opinions

### ISSUE THREAD

**Issue by amith-ananthram** [jerbarnes/semeval22_structured_sentiment#3]
Hey there!  Sorry to spam you -- just wanted to call out that the dev split of MPQA that process_mpqa.sh produces contains no opinions.  Not sure if that's expected -- I can just use part of the training split as my dev set so not a big issue but just wanted to draw your attention to it.  Thanks!

```
>>> with open('dev.json', 'r') as f:
...   dev = json.load(f)
... 
>>> c = Counter()
>>> for sentence in dev:
...   c[len(sentence['opinions'])] += 1
... 
>>> c
Counter({0: 2024})
```

**Comment by jerbarnes** [comment]
Hey, no problem. You're correct. As the shared task is currently in the development phase, we have not released the dev annotations yet. When we start the evaluation phase, we'll release all the annotations.

**Comment by amith-ananthram** [comment]
Ah understood, thank you!
